### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by Emkay27** [hex-hypercity/Moodle-forum#6]
The issue that we have is that the coverall doesn't increase from 0% even though the tests work perfectly on Travis-ci it keeps saying 0 of 102 relevant lines covered (0.0%) on coveralls,this issue is persistent even though the composer dump-autoload says Generated autoload files containing 627 classes.

**Comment by Khomotjo4** [comment]
Coverall has increased but have do more test cases

**Comment by Emkay27** [comment]
We have done more tests for sprint 4.
